# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 352b8784b405cc54239e1629cf5685dd493184eae54c107ef5d219b896af9ad7879241a5a9e05cd4a532b878a2bf9037224beda1377074b83d0bdcd4a0e63a91

test:
  secret_key_base: e18a52445cf9678c4fb6d7c2ad7c428893682eaeed46d8016b64390db91f625a3f8ae7132b3840863857b06d37108c4aedf8ab58392c8eeeb9f530595e1bf184

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
